[toolchain]
channel = "stable"
profile = "default"
targets = [ "i686-pc-windows-gnu", "x86_64-pc-windows-gnu", "i686-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "arm-unknown-linux-gnueabihf", "x86_64-apple-darwin", "aarch64-apple-darwin" ]
